#!/bin/bash

# a launcher script for the X11 GUI even if you are already in an ssh session
# https://stackoverflow.com/questions/48235040/run-x-application-in-a-docker-container-reliably-on-a-server-connected-via-ssh-w

thisdir=$(realpath $(dirname ${BASH_SOURCE[0]}))

XSOCK=/tmp/.X11-unix # X11 socket (but we mount the whole of tmp)
XAUTH=/tmp/.container.xauth.$USER
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
chmod 777 $XAUTH


x11="
-e DISPLAY
-v $XAUTH:$XAUTH
-e XAUTHORITY=$XAUTH
--net host
"

args="
-it
--security-opt=label=type:container_runtime_t
-w $(pwd)
"

export MYHOME=/home/${USER}
mounts="
-v=$(pwd):$(pwd)
-v=/tmp:/tmp
-v=${MYHOME}:${MYHOME}
-v=${MYHOME}/.ssh:/root/.ssh
-v=${MYHOME}/.bash_history:/root/.bash_history
-v=${thisdir}/.bashrc_dev:/root/.bashrc
-v=${thisdir}/.inputrc:/root/.inputrc
-v=${thisdir}/cli-tools:/cli-tools
-v=${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
"

podman run ${mounts} ${args} ${x11} dev-e7
