#!/bin/bash

# start a podman rootful service to serve docker clients inside this container

if [[ -f /var/run/docker.sock ]] ; then
    echo "already started. (delete /var/run/docker.sock to retry)"
else
    podman network create default
    mkdir -p /var/run/
    touch /var/run/docker.sock
    nohup podman system service --time 0 unix:///var/run/docker.sock > ~/.podman_service.log &
fi

